### ISSUE TITLE
Problems using ts-enum-utils with typeorm and nestJS

### ISSUE THREAD

**Issue by acepace** [UselessPickles/ts-enum-util#15]
Trying to use ts-enum-utils to describe types imported by typeorm.

The error I receive is
```
import { $enum } from 'ts-enum-util'
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

The tsconfig.json file was generated by nestjs\cli and looks like this.

```
{ 
   {
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es2017",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "resolveJsonModule": true
  },
  "exclude": ["node_modules", "dist"]
}
```

What am I doing wrong?

**Comment by UselessPickles** [comment]
I don't know. That has to be related to typescript compiler settings, how you're executing `tsc`, what kind of file you wrote that code in, etc., and you would get the same error trying to import anything from any library. This has nothing to do with `ts-enum-util`.
