### ISSUE TITLE
fail push new version???

### ISSUE THREAD

**Issue by bluelovers** [UselessPickles/ts-enum-util#4]
```
D:.
│  LICENSE
│  package.json
│  README.md
│
├─dist
│  └─types
│          index.d.ts
│          index.d.ts.map
│
└─src
        index.ts
```

forgot push or build js file??

**Comment by UselessPickles** [comment]
Thanks for reporting the problem. I should probably be more awake when I publish :)

This should be fixed by version 3.0.6: https://github.com/UselessPickles/ts-enum-util/releases/tag/v3.0.6
